<a href="https://colab.research.google.com/github/heernink/DPatch/blob/master/v2_patch_real.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/minji-o-j/YOLOv2.git

Cloning into 'YOLOv2'...
remote: Enumerating objects: 440, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 440 (delta 41), reused 68 (delta 26), pack-reused 347
Receiving objects: 100% (440/440), 83.77 MiB | 37.33 MiB/s, done.
Resolving deltas: 100% (145/145), done.


In [2]:
!nvidia-smi

Sun Apr 16 07:21:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
%cd /content/YOLOv2
!pip install -r requirements.txt

/content/YOLOv2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 3.9 MB/s eta 0:00:00


In [4]:
!wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
!wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
!wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCdevkit_08-Jun-2007.tar
    # download 2012 data
!wget http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar

--2023-04-16 07:21:07--  http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 460032000 (439M) [application/x-tar]
Saving to: ‘VOCtrainval_06-Nov-2007.tar’

VOCtrainval_06-Nov- 100%[===================>] 438.72M  29.3MB/s    in 16s     

2023-04-16 07:21:23 (27.5 MB/s) - ‘VOCtrainval_06-Nov-2007.tar’ saved [460032000/460032000]

--2023-04-16 07:21:23--  http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 451020800 (430M) [application/x-tar]
Saving to: ‘VOCtest_06-Nov-2007.tar’

VOCtest_06-Nov-2007 100%[===================

In [5]:
!tar xvf VOCtrainval_06-Nov-2007.tar
!tar xvf VOCtest_06-Nov-2007.tar
!tar xvf VOCdevkit_08-Jun-2007.tar

# 2012 data
!tar xvf VOCtrainval_11-May-2012.tar

Streaming output truncated to the last 5000 lines.
VOCdevkit/VOC2012/SegmentationClass/2008_001874.png
VOCdevkit/VOC2012/SegmentationClass/2008_001876.png
VOCdevkit/VOC2012/SegmentationClass/2008_001882.png
VOCdevkit/VOC2012/SegmentationClass/2008_001885.png
VOCdevkit/VOC2012/SegmentationClass/2008_001895.png
VOCdevkit/VOC2012/SegmentationClass/2008_001896.png
VOCdevkit/VOC2012/SegmentationClass/2008_001926.png
VOCdevkit/VOC2012/SegmentationClass/2008_001966.png
VOCdevkit/VOC2012/SegmentationClass/2008_001971.png
VOCdevkit/VOC2012/SegmentationClass/2008_001992.png
VOCdevkit/VOC2012/SegmentationClass/2008_001997.png
VOCdevkit/VOC2012/SegmentationClass/2008_002032.png
VOCdevkit/VOC2012/SegmentationClass/2008_002043.png
VOCdevkit/VOC2012/SegmentationClass/2008_002064.png
VOCdevkit/VOC2012/SegmentationClass/2008_002066.png
VOCdevkit/VOC2012/SegmentationClass/2008_002067.png
VOCdevkit/VOC2012/SegmentationClass/2008_002073.png
VOCdevkit/VOC2012/SegmentationClass/2008_002079.png
VOCdevkit/VOC

In [9]:
!wget http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar

--2023-04-16 07:26:38--  http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar
Resolving host.robots.ox.ac.uk (host.robots.ox.ac.uk)... 129.67.94.152
Connecting to host.robots.ox.ac.uk (host.robots.ox.ac.uk)|129.67.94.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 451020800 (430M) [application/x-tar]
Saving to: ‘VOCtest_06-Nov-2007.tar.2’

VOCtest_06-Nov-2007 100%[===================>] 430.13M  26.0MB/s    in 25s     

2023-04-16 07:27:03 (17.1 MB/s) - ‘VOCtest_06-Nov-2007.tar.2’ saved [451020800/451020800]



In [10]:
!tar xvf VOCtest_06-Nov-2007.tar

Streaming output truncated to the last 5000 lines.
VOCdevkit/VOC2007/JPEGImages/000725.jpg
VOCdevkit/VOC2007/JPEGImages/000727.jpg
VOCdevkit/VOC2007/JPEGImages/000732.jpg
VOCdevkit/VOC2007/JPEGImages/000734.jpg
VOCdevkit/VOC2007/JPEGImages/000735.jpg
VOCdevkit/VOC2007/JPEGImages/000736.jpg
VOCdevkit/VOC2007/JPEGImages/000737.jpg
VOCdevkit/VOC2007/JPEGImages/000741.jpg
VOCdevkit/VOC2007/JPEGImages/000743.jpg
VOCdevkit/VOC2007/JPEGImages/000744.jpg
VOCdevkit/VOC2007/JPEGImages/000745.jpg
VOCdevkit/VOC2007/JPEGImages/000747.jpg
VOCdevkit/VOC2007/JPEGImages/000749.jpg
VOCdevkit/VOC2007/JPEGImages/000751.jpg
VOCdevkit/VOC2007/JPEGImages/000757.jpg
VOCdevkit/VOC2007/JPEGImages/000758.jpg
VOCdevkit/VOC2007/JPEGImages/000759.jpg
VOCdevkit/VOC2007/JPEGImages/000762.jpg
VOCdevkit/VOC2007/JPEGImages/000765.jpg
VOCdevkit/VOC2007/JPEGImages/000766.jpg
VOCdevkit/VOC2007/JPEGImages/000769.jpg
VOCdevkit/VOC2007/JPEGImages/000773.jpg
VOCdevkit/VOC2007/JPEGImages/000775.jpg
VOCdevkit/VOC2007/JPEGImages/

In [15]:
with open('/content/YOLOv2/VOCdevkit/VOC2007/ImageSets/Main/tvmonitor_test.txt', 'r') as f:
  data = f.readlines()

len(data)

4952

In [61]:
with open('/content/YOLOv2/VOCdevkit/VOC2007/ImageSets/Main/tvmonitor_test.txt', 'r') as f:
  data = f.readlines()

tmp = []
for i in range(len(data)):
  tmp.append(data[i])

number = []

for i in range(len(data)):
  if tmp[i][-3] == ' ':
    number.append(tmp[i][:6])
    file_list = [f"{num}.jpg" for num in number]

file_list



['000045.jpg',
 '000059.jpg',
 '000185.jpg',
 '000204.jpg',
 '000227.jpg',
 '000265.jpg',
 '000291.jpg',
 '000342.jpg',
 '000397.jpg',
 '000414.jpg',
 '000421.jpg',
 '000571.jpg',
 '000644.jpg',
 '000659.jpg',
 '000758.jpg',
 '000790.jpg',
 '000813.jpg',
 '000956.jpg',
 '000961.jpg',
 '000974.jpg',
 '000994.jpg',
 '001007.jpg',
 '001029.jpg',
 '001039.jpg',
 '001081.jpg',
 '001138.jpg',
 '001338.jpg',
 '001363.jpg',
 '001367.jpg',
 '001392.jpg',
 '001459.jpg',
 '001500.jpg',
 '001513.jpg',
 '001546.jpg',
 '001549.jpg',
 '001551.jpg',
 '001572.jpg',
 '001695.jpg',
 '001704.jpg',
 '001742.jpg',
 '001763.jpg',
 '001811.jpg',
 '001813.jpg',
 '001824.jpg',
 '001826.jpg',
 '001871.jpg',
 '001905.jpg',
 '001961.jpg',
 '002062.jpg',
 '002073.jpg',
 '002074.jpg',
 '002081.jpg',
 '002093.jpg',
 '002119.jpg',
 '002227.jpg',
 '002252.jpg',
 '002258.jpg',
 '002282.jpg',
 '002356.jpg',
 '002394.jpg',
 '002430.jpg',
 '002469.jpg',
 '002503.jpg',
 '002601.jpg',
 '002608.jpg',
 '002617.jpg',
 '002638.j

In [18]:
data[0]

'000001 -1\n'

In [62]:
!wget https://pjreddie.com/media/files/darknet19_448.weights

--2023-04-16 08:21:03--  https://pjreddie.com/media/files/darknet19_448.weights
Resolving pjreddie.com (pjreddie.com)... 128.208.4.108
Connecting to pjreddie.com (pjreddie.com)|128.208.4.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83427120 (80M) [application/octet-stream]
Saving to: ‘darknet19_448.weights’

darknet19_448.weigh 100%[===================>]  79.56M  42.2MB/s    in 1.9s    

2023-04-16 08:21:05 (42.2 MB/s) - ‘darknet19_448.weights’ saved [83427120/83427120]



In [63]:
!wget http://pjreddie.com/media/files/yolo-voc.weights

URL transformed to HTTPS due to an HSTS policy
--2023-04-16 08:21:05--  https://pjreddie.com/media/files/yolo-voc.weights
Resolving pjreddie.com (pjreddie.com)... 128.208.4.108
Connecting to pjreddie.com (pjreddie.com)|128.208.4.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 202704260 (193M) [application/octet-stream]
Saving to: ‘yolo-voc.weights’

yolo-voc.weights    100%[===================>] 193.31M  59.3MB/s    in 3.5s    

2023-04-16 08:21:09 (55.0 MB/s) - ‘yolo-voc.weights’ saved [202704260/202704260]



In [100]:
with open('/content/YOLOv2/VOCdevkit/VOC2007/ImageSets/Main/tvmonitor_test.txt', 'r') as f:
  data = f.readlines()

tmp = []
for i in range(len(data)):
  tmp.append(data[i])

number = []

for i in range(len(data)):
  if tmp[i][-3] == ' ':
    number.append(tmp[i][:6])
    file_list = [f"{num}.jpg" for num in number]

print(file_list)

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [101]:
file_list.index('001546.jpg')

33

In [97]:
100/244*100

40.98360655737705

In [84]:
!python demo.py

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [98]:
!python demo.py --cuda true

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [99]:
!python demo.py --cuda true

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [102]:
!python demo.py --cuda true

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [103]:
!python demo.py --cuda true

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [104]:
!python demo.py --cuda true

['000045.jpg', '000059.jpg', '000185.jpg', '000204.jpg', '000227.jpg', '000265.jpg', '000291.jpg', '000342.jpg', '000397.jpg', '000414.jpg', '000421.jpg', '000571.jpg', '000644.jpg', '000659.jpg', '000758.jpg', '000790.jpg', '000813.jpg', '000956.jpg', '000961.jpg', '000974.jpg', '000994.jpg', '001007.jpg', '001029.jpg', '001039.jpg', '001081.jpg', '001138.jpg', '001338.jpg', '001363.jpg', '001367.jpg', '001392.jpg', '001459.jpg', '001500.jpg', '001513.jpg', '001546.jpg', '001549.jpg', '001551.jpg', '001572.jpg', '001695.jpg', '001704.jpg', '001742.jpg', '001763.jpg', '001811.jpg', '001813.jpg', '001824.jpg', '001826.jpg', '001871.jpg', '001905.jpg', '001961.jpg', '002062.jpg', '002073.jpg', '002074.jpg', '002081.jpg', '002093.jpg', '002119.jpg', '002227.jpg', '002252.jpg', '002258.jpg', '002282.jpg', '002356.jpg', '002394.jpg', '002430.jpg', '002469.jpg', '002503.jpg', '002601.jpg', '002608.jpg', '002617.jpg', '002638.jpg', '002656.jpg', '002752.jpg', '002792.jpg', '002809.jpg', '0028

In [61]:
!python train.py --cuda true

Streaming output truncated to the last 5000 lines.
           -8.8562e-43, -4.7644e-44],
          [-6.7186e-01, -2.7076e-01,  1.1519e-01,  ..., -4.5682e-43,
           -1.4854e-42, -3.5593e-43],
          [-1.1884e+00, -1.7275e+00, -8.1284e-01,  ..., -4.9326e-43,
           -9.6690e-43, -3.6994e-43],
          ...,
          [-4.9606e-43, -4.3160e-43, -4.0077e-43,  ..., -5.6332e-43,
           -3.2230e-43, -1.5078e-42],
          [-8.8842e-43, -8.2677e-43, -7.3148e-43,  ..., -4.3440e-43,
           -5.3249e-43, -3.9797e-43],
          [-3.6714e-43, -8.2396e-43, -9.6129e-43,  ..., -1.2612e-42,
           -5.8014e-43, -1.2556e-42]],

         [[ 9.4346e-01,  1.4884e+00,  7.0453e-01,  ..., -6.7543e-43,
           -1.0145e-42, -1.2752e-42],
          [-5.9842e-01,  2.3126e-01,  1.3869e-01,  ..., -8.0154e-43,
           -4.9045e-43, -6.7543e-43],
          [-9.7055e-01, -1.2569e+00, -2.3806e-01,  ..., -3.8115e-43,
           -4.0077e-43, -1.0986e-42],
          ...,
          [-1.0426e-42,

In [ ]:
no change weight it's mang same upp down
down is epoch1's  sttart
up is epcoh2's start

up ddown is same

In [ ]:
!python train.py --cuda true

--------------- patch saved in ----------------
trained_patch/1
cuda:0
Called with args:
Namespace(max_epochs=100, start_epoch=1, dataset='voc0712trainval', num_workers=8, output_dir='output', use_tfboard=False, display_interval=10, mGPUs=False, save_interval=1, use_cuda=True, resume=False, checkpoint_epoch=160, exp_name='default', lr=0.0001, decay_lrs={60: 1e-05, 90: 1e-06}, weight_decay=0.0005, momentum=0.9, batch_size=16, pretrained_model='data/pretrained/darknet19_448.weights')
loading dataset....
voc_2007_trainval gt roidb loaded from /content/YOLOv2/data/cache/voc_2007_trainval_gt_roidb.pkl
load dataset voc_2007_trainval
voc_2012_trainval gt roidb loaded from /content/YOLOv2/data/cache/voc_2012_trainval_gt_roidb.pkl
load and add dataset voc_2012_trainval
dataset loaded.
training rois number: 16551
/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in cu

In [44]:
import numpy

box =[[[0., 0., 120., 120.],
      [0., 0., 120., 120.],
      [0., 0., 120., 120.]],
      [[0., 0., 0., 0.],
      [0., 0., 120., 120.],
      [0., 0., 120., 120.]]]
box = numpy.array(box)
print(box[:, 2])
print(box[:, 0])
print(box[:, 2] + box[:, 0])

[[  0.   0. 120. 120.]
 [  0.   0. 120. 120.]]
[[  0.   0. 120. 120.]
 [  0.   0.   0.   0.]]
[[  0.   0. 240. 240.]
 [  0.   0. 120. 120.]]


In [47]:
import numpy

box =[[0., 0., 120., 120.],
      [0., 0., 120., 120.],
      [0., 0., 120., 120.]]
box = numpy.array(box)
print(box.shape)
print(box[:, 2])
print(box[:, 0])
print(box[:, 2] + box[:, 0])

(3, 4)
[120. 120. 120.]
[0. 0. 0.]
[120. 120. 120.]


In [54]:
import torch
box =[[0., 0., 120., 120.],
      [0., 0., 120., 120.],
      [0., 0., 120., 120.]]

box = numpy.array(box)

c_x = (box[:, 2] + box[:, 0]) / 2
c_y = (box[:, 3] + box[:, 1]) / 2
w = box[:, 2] - box[:, 0]
h = box[:, 3] - box[:, 1]

c_x = torch.FloatTensor(c_x)
c_y = torch.FloatTensor(c_y)
w = torch.FloatTensor(w)
h = torch.FloatTensor(h)

c_x = c_x.view(-1, 1)
print(c_x)
c_y = c_y.view(-1, 1)
print(c_y)
w = w.view(-1, 1)
h = h.view(-1, 1)

xywh_box = torch.cat([c_x, c_y, w, h], dim=1)
print(xywh_box )

tensor([[60.],
        [60.],
        [60.]])
tensor([[60.],
        [60.],
        [60.]])
tensor([[ 60.,  60., 120., 120.],
        [ 60.,  60., 120., 120.],
        [ 60.,  60., 120., 120.]])


In [ ]:
!python train.py --cuda true

--------------- patch saved in ----------------
trained_patch/4
cuda:0
Called with args:
Namespace(max_epochs=100, start_epoch=1, dataset='voc0712trainval', num_workers=8, output_dir='output', use_tfboard=False, display_interval=10, mGPUs=False, save_interval=1, use_cuda=True, resume=False, checkpoint_epoch=160, exp_name='default', lr=0.0001, decay_lrs={60: 1e-05, 90: 1e-06}, weight_decay=0.0005, momentum=0.9, batch_size=16, pretrained_model='data/pretrained/darknet19_448.weights')
loading dataset....
voc_2007_trainval gt roidb loaded from /content/YOLOv2/data/cache/voc_2007_trainval_gt_roidb.pkl
load dataset voc_2007_trainval
voc_2012_trainval gt roidb loaded from /content/YOLOv2/data/cache/voc_2012_trainval_gt_roidb.pkl
load and add dataset voc_2012_trainval
dataset loaded.
training rois number: 16551
/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py:561: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in cu

In [ ]:

with open('/content/YOLOv2/VOCdevkit/VOC2007/ImageSets/Main/tvmonitor_test.txt', 'r') as f:
  data = f.readlines()

tmp = []
for i in range(len(data)):
  tmp.append(data[i])

number = []

for i in range(len(data)):
  if tmp[i][-3] == ' ':
    number.append(tmp[i][:6])
    file_list = [f"{num}.jpg" for num in number]

file_list

In [ ]:
from PIL import Image

sample = Image.open('/content/yolov3/data/images/zidane.jpg')
patch = Image.open('/content/yolov3/data/images/duplicate2.png')
patch = patch.resize((120, 120))
print(patch.size)

area = (0, 0, 120, 120)
sample.paste(patch, area)
sample.save('/content/yolov3/data/images/new.png')

(120, 120)


In [ ]:
!python demo.py

call with args: Namespace(output_dir='output', model_name='yolov2_epoch_20', use_cuda=False)
loading model from output/yolov2_epoch_20.pth
model loaded
/usr/local/lib/python3.9/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
im detect, cost time 0.639836, FPS: 1
Figure(640x480)
[[8.53824463e+01 1.42401123e+01 4.13611084e+02 3.17665466e+02
  3.11684996e-01]
 [1.67126755e+02 6.94563217e+01 3.36751648e+02 1.28747650e+02
  5.13594709e-02]
 [1.06407822e+02 6.90299530e+01 3.92620300e+02 1.93288742e+02
  2.96844058e-02]
 [3.26084290e+01 4.91283417e+01 4.74097931e+02 1.55530045e+02
  1.88571773e-02]
 [2.97912201e+02 0.00000000e+00 4.22790314e+02 5.08794937e+01
  9.39793587e-02]
 [4.02910065e+02 2.73888763e+02 4.85848663e+02 3.74000000e+02
  4.94049564e-02]
 [4

In [ ]:
!python test.py

Streaming output truncated to the last 5000 lines.
im detect [77/4952]
im detect [78/4952]
im detect [79/4952]
im detect [80/4952]
im detect [81/4952]
im detect [82/4952]
im detect [83/4952]
im detect [84/4952]
im detect [85/4952]
im detect [86/4952]
im detect [87/4952]
im detect [88/4952]
im detect [89/4952]
im detect [90/4952]
im detect [91/4952]
im detect [92/4952]
im detect [93/4952]
im detect [94/4952]
im detect [95/4952]
im detect [96/4952]
im detect [97/4952]
im detect [98/4952]
im detect [99/4952]
im detect [100/4952]
im detect [101/4952]
im detect [102/4952]
im detect [103/4952]
im detect [104/4952]
im detect [105/4952]
im detect [106/4952]
im detect [107/4952]
im detect [108/4952]
im detect [109/4952]
im detect [110/4952]
im detect [111/4952]
im detect [112/4952]
im detect [113/4952]
im detect [114/4952]
im detect [115/4952]
im detect [116/4952]
im detect [117/4952]
im detect [118/4952]
im detect [119/4952]
im detect [120/4952]
im detect [121/4952]
im detect [122/4952]
im det

In [ ]:
!python test.py --cuda true

Streaming output truncated to the last 5000 lines.
im detect [26/4952]
im detect [27/4952]
im detect [28/4952]
im detect [29/4952]
im detect [30/4952]
im detect [31/4952]
im detect [32/4952]
im detect [33/4952]
im detect [34/4952]
im detect [35/4952]
im detect [36/4952]
im detect [37/4952]
im detect [38/4952]
im detect [39/4952]
im detect [40/4952]
im detect [41/4952]
im detect [42/4952]
im detect [43/4952]
im detect [44/4952]
im detect [45/4952]
im detect [46/4952]
im detect [47/4952]
im detect [48/4952]
im detect [49/4952]
im detect [50/4952]
im detect [51/4952]
im detect [52/4952]
im detect [53/4952]
im detect [54/4952]
im detect [55/4952]
im detect [56/4952]
im detect [57/4952]
im detect [58/4952]
im detect [59/4952]
im detect [60/4952]
im detect [61/4952]
im detect [62/4952]
im detect [63/4952]
im detect [64/4952]
im detect [65/4952]
im detect [66/4952]
im detect [67/4952]
im detect [68/4952]
im detect [69/4952]
im detect [70/4952]
im detect [71/4952]
im detect [72/4952]
im detect

In [ ]:
!python test.py --cuda true

Streaming output truncated to the last 5000 lines.
im detect [26/4952]
im detect [27/4952]
im detect [28/4952]
im detect [29/4952]
im detect [30/4952]
im detect [31/4952]
im detect [32/4952]
im detect [33/4952]
im detect [34/4952]
im detect [35/4952]
im detect [36/4952]
im detect [37/4952]
im detect [38/4952]
im detect [39/4952]
im detect [40/4952]
im detect [41/4952]
im detect [42/4952]
im detect [43/4952]
im detect [44/4952]
im detect [45/4952]
im detect [46/4952]
im detect [47/4952]
im detect [48/4952]
im detect [49/4952]
im detect [50/4952]
im detect [51/4952]
im detect [52/4952]
im detect [53/4952]
im detect [54/4952]
im detect [55/4952]
im detect [56/4952]
im detect [57/4952]
im detect [58/4952]
im detect [59/4952]
im detect [60/4952]
im detect [61/4952]
im detect [62/4952]
im detect [63/4952]
im detect [64/4952]
im detect [65/4952]
im detect [66/4952]
im detect [67/4952]
im detect [68/4952]
im detect [69/4952]
im detect [70/4952]
im detect [71/4952]
im detect [72/4952]
im detect

In [ ]:
!python test.py --cuda true

Streaming output truncated to the last 5000 lines.
im detect [26/4952]
im detect [27/4952]
im detect [28/4952]
im detect [29/4952]
im detect [30/4952]
im detect [31/4952]
im detect [32/4952]
im detect [33/4952]
im detect [34/4952]
im detect [35/4952]
im detect [36/4952]
im detect [37/4952]
im detect [38/4952]
im detect [39/4952]
im detect [40/4952]
im detect [41/4952]
im detect [42/4952]
im detect [43/4952]
im detect [44/4952]
im detect [45/4952]
im detect [46/4952]
im detect [47/4952]
im detect [48/4952]
im detect [49/4952]
im detect [50/4952]
im detect [51/4952]
im detect [52/4952]
im detect [53/4952]
im detect [54/4952]
im detect [55/4952]
im detect [56/4952]
im detect [57/4952]
im detect [58/4952]
im detect [59/4952]
im detect [60/4952]
im detect [61/4952]
im detect [62/4952]
im detect [63/4952]
im detect [64/4952]
im detect [65/4952]
im detect [66/4952]
im detect [67/4952]
im detect [68/4952]
im detect [69/4952]
im detect [70/4952]
im detect [71/4952]
im detect [72/4952]
im detect

In [ ]:
!python test.py --cuda true

Streaming output truncated to the last 5000 lines.
im detect [77/4952]
im detect [78/4952]
im detect [79/4952]
im detect [80/4952]
im detect [81/4952]
im detect [82/4952]
im detect [83/4952]
im detect [84/4952]
im detect [85/4952]
im detect [86/4952]
im detect [87/4952]
im detect [88/4952]
im detect [89/4952]
im detect [90/4952]
im detect [91/4952]
im detect [92/4952]
im detect [93/4952]
im detect [94/4952]
im detect [95/4952]
im detect [96/4952]
im detect [97/4952]
im detect [98/4952]
im detect [99/4952]
im detect [100/4952]
im detect [101/4952]
im detect [102/4952]
im detect [103/4952]
im detect [104/4952]
im detect [105/4952]
im detect [106/4952]
im detect [107/4952]
im detect [108/4952]
im detect [109/4952]
im detect [110/4952]
im detect [111/4952]
im detect [112/4952]
im detect [113/4952]
im detect [114/4952]
im detect [115/4952]
im detect [116/4952]
im detect [117/4952]
im detect [118/4952]
im detect [119/4952]
im detect [120/4952]
im detect [121/4952]
im detect [122/4952]
im det

In [ ]:
######## 패치 불러오기 ########
patch = Image.open('/Data2/hm22/DPatch/trained_patch/14/5011.png')

######## yolo 불러오기 ########
from yolov2 import Yolov2
import os

pretrained_model = os.path.join('/Data1/sm21/transform_based_defense/YOLOv2/dataset/data/pretrained', 'darknet19_448.weights')

patch_np = np.array(patch)
patch_np.shape
patch_np = patch_np.transpose((2,0,1))
patch_np.shape
patch_t = torch.from_numpy(patch_np)



####### defense 코드 ########
def test_dpatch_loc_masking():
    args = parse_args()
    args.conf_thresh = 0.005
    args.nms_thresh = 0.45
    if args.vis:
        args.conf_thresh = 0.5
    print('Called with args:')
    print(args)

    # prepare dataset

#     if args.dataset == 'voc07trainval':
#         args.imdbval_name = 'voc_2007_trainval'

#     elif args.dataset == 'voc07test':
#         args.imdbval_name = 'voc_2007_test'

#     else:
#         raise NotImplementedError

#     val_imdb = get_imdb(args.imdbval_name)

#     val_dataset = RoiDataset(val_imdb, train=False)
#     val_dataloader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False)
       
    val_imdb = get_imdb('voc_2007_test')
    val_dataset = RoiDataset(val_imdb, train=False)
    val_dataloader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False)
   
    # load model
    pretrained_model = os.path.join('/Data1/sm21/transform_based_defense/YOLOv2/dataset/data/pretrained', 'darknet19_448.weights')
    model = Yolov2(weights_file=pretrained_model)
#     model = Yolov2()
#     weight_loader = WeightLoader()
#     weight_loader.load(model, pretrained_model)
    # print('loaded')

    model_path = os.path.join(args.output_dir, args.model_name+'.pth')
    print('loading model from {}'.format(model_path))
    if torch.cuda.is_available():
        checkpoint = torch.load(model_path)
    else:
        checkpoint = torch.load(model_path, map_location='cpu')
    model.load_state_dict(checkpoint['model'])

    if args.use_cuda:
        model.cuda()

    model.eval()
    print('model loaded')

    dataset_size = len(val_imdb.image_index)

    all_boxes = [[[] for _ in range(dataset_size)] for _ in range(val_imdb.num_classes)]

    det_file = os.path.join(args.output_dir, 'detections.pkl')

    img_id = -1
    with torch.no_grad():
        for batch, (im_data, im_infos) in enumerate(val_dataloader):
            if args.use_cuda:
#                 print(im_data.shape)
                im_data_variable = Variable(im_data).cuda()
            else:
#                 print(im_data.shape)
                s1, s2 = patch_t.shape[2], patch_t.shape[2]
#                 print(s1,s2)
                im_data[:,:,0:s1,0:s2] = patch_t
#                 print(im_data.shape)
#                 print(im_data.dtype)
               
   
                window_size = 3
                stride = 3
#                 print(im_data)
                ker_var_list = []
                for i in range(0,im_data.shape[3],stride):
                    for j in range(0,im_data.shape[2],stride):
#                         print(j,i)
                        ker = im_data[:,:,j:min(im_data.shape[2],j+window_size),i:min(im_data.shape[3],i+window_size)]
#                         print(ker)
#                         print(torch.var_mean(ker)[0])
#                         print(ker)
                        ker_var_list.append(torch.var_mean(ker)[0])
#                 print(ker_var_list)
                ker_var_np = np.array(ker_var_list)
                limit_var_lower = ker_var_np.mean()- (ker_var_np.std()*3)
                limit_var_upper = ker_var_np.mean()+ (ker_var_np.std()*3)
#                 print(limit_var_upper)
               
               
                wit = torch.ones(im_data.shape)

                x_coor = []
                y_coor = []
#                 print(im_data.shape)
                for i in range(0,im_data.shape[3],stride):
                    for j in range(0,im_data.shape[2],stride):
                        ker = im_data[:,:,j:min(im_data.shape[2],j+window_size),i:min(im_data.shape[3],i+window_size)]
                        ker_var = torch.var_mean(ker)[0]
#                         print(limit_var_upper)
#         print(j,i)
                        if ker_var > limit_var_upper:
#                             print(limit_var_upper)
                            x_coor.append(j)
                            y_coor.append(i)
                            wit[j:min(im_data.shape[2],j+window_size),i:min(im_data.shape[3],i+window_size)]=0
                        if ker_var < limit_var_lower:
                            x_coor.append(j)
                            y_coor.append(i)
                            wit[j:min(im_data.shape[2],j+window_size),i:min(im_data.shape[3],i+window_size)]=0
#                 print(x_coor)            
                coor = pd.DataFrame({'x_coor':x_coor, 'y_coor':y_coor})
                loc_data = StandardScaler().fit_transform(coor[['x_coor','y_coor']])
                clustering = DBSCAN(eps=0.5, min_samples=5).fit(loc_data)
#                 print(len(clustering.labels_))
                coor['clust'] = clustering.labels_
                max_idx = np.argmax(coor['clust'].value_counts())
#                 print(max_idx)
                coor_m = coor[coor["clust"]==max_idx]
               
                x_min = min(coor_m["x_coor"])
                y_min = min(coor_m["y_coor"])
                x_max = max(coor_m["x_coor"])+window_size
                y_max = max(coor_m["y_coor"])+window_size
               
               
                im_data[:,:,x_min:x_max, y_min:y_max] = 0
               
                im_data_variable = Variable(im_data)

            yolo_outputs = model(im_data_variable)
            for i in range(im_data.size(0)):
                img_id += 1
                output = [item[i].data for item in yolo_outputs]
                im_info = {'width': im_infos[i][0], 'height': im_infos[i][1]}
                detections = yolo_eval(output, im_info, conf_threshold=args.conf_thresh,
                                       nms_threshold=args.nms_thresh)
                print('im detect [{}/{}]'.format(img_id+1, len(val_dataset)))
                if len(detections) > 0:
                    for cls in range(val_imdb.num_classes):
                        inds = torch.nonzero(detections[:, -1] == cls).view(-1)
                        if inds.numel() > 0:
                            cls_det = torch.zeros((inds.numel(), 5))
                            cls_det[:, :4] = detections[inds, :4]
                            cls_det[:, 4] = detections[inds, 4] * detections[inds, 5]
                            all_boxes[cls][img_id] = cls_det.cpu().numpy()

                if args.vis:
                    img = Image.open(val_imdb.image_path_at(img_id))
                    if len(detections) == 0:
                        continue
                    det_boxes = detections[:, :5].cpu().numpy()
                    det_classes = detections[:, -1].long().cpu().numpy()
                    im2show = draw_detection_boxes(img, det_boxes, det_classes, class_names=val_imdb.classes)
                    plt.figure()
                    plt.imshow(im2show)
                    plt.show()

    with open(det_file, 'wb') as f:
        pickle.dump(all_boxes, f, pickle.HIGHEST_PROTOCOL)

    val_imdb.evaluate_detections(all_boxes, output_dir=args.output_dir)





######## defense 코드 실행 ########
import argparse
from torch.autograd import Variable
from dataset.factory import get_imdb
from torch.utils.data import DataLoader
from dataset.roidb import RoiDataset
from util.network import WeightLoader
from yolo_eval import yolo_eval
import torch
import pickle

def parse_args():

    parser = argparse.ArgumentParser('Yolo v2')
    parser.add_argument('--dataset', dest='dataset',
                        default='voc07test', type=str)
    parser.add_argument('--output_dir', dest='output_dir',
                        default='output', type=str)
    parser.add_argument('--model_name', dest='model_name',
                        default='yolov2_epoch_20', type=str)
    parser.add_argument('--nw', dest='num_workers',
                        help='number of workers to load training data',
                        default=0, type=int)
    parser.add_argument('--bs', dest='batch_size',
                        default=1, type=int)
    parser.add_argument('--cuda', dest='use_cuda',
                        default=False, type=bool)
    parser.add_argument('--vis', dest='vis',
                        default=False, type=bool)

    args = parser.parse_args([])
    return args



start = torch.cuda.Event(enable_timing=True)
end = torch.cuda.Event(enable_timing=True)

start.record()
test_dpatch_loc_masking()
end.record()

# Waits for everything to finish running
torch.cuda.synchronize()

print(start.elapsed_time(end))